export const GET_ERRORS = 'GET_ERRORS';
export const GET_INTERVIEWS = 'GET_INTERVIEWS';
export const GET_INTERVIEW = 'GET_INTERVIEW';
export const DELETE_INTERVIEW = 'DELETE_INTERVIEW';

// Types for Backlog

export const GET_BACKLOG = 'GET_BACKLOG';
export const GET_INTERVIEW_TASK = 'GET_INTERVIEW_TASK';
export const DELETE_INTERVIEW_TASK = 'DELETE_INTERVIEW_TASK';
